-- 테이블 생성
CREATE TABLE MEMBER (
    MEMBER_PK VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(20),
    AGE VARCHAR(20),
    GENDER VARCHAR(20),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(20)
);

CREATE TABLE HOBBY (
    HOBBY_PK VARCHAR(20) PRIMARY KEY,
    HOBBY_NAME VARCHAR(20)
);

CREATE TABLE ADDRESS (
    ADDRESS_PK VARCHAR(20) PRIMARY KEY,
    ADDRESS_NAME VARCHAR(20)
);

CREATE TABLE MEMBER_INFO (
    MEMBER_INFO_PK VARCHAR(10) PRIMARY KEY,
    MEMBER_FK VARCHAR(20),
    HOBBY_FK VARCHAR(20),
    ADDRESS_FK VARCHAR(20),
    FOREIGN KEY (MEMBER_FK) REFERENCES MEMBER(MEMBER_PK),
    FOREIGN KEY (HOBBY_FK) REFERENCES HOBBY(HOBBY_PK) ,
    FOREIGN KEY (ADDRESS_FK) REFERENCES ADDRESS(ADDRESS_PK)
);

