
-- 테이블 생성
CREATE TABLE `COMPANY` (
    `COMPANY_INFORMATION_PK` VARCHAR(20) NOT NULL,
    `COMPANY_NAME` VARCHAR(20) NOT NULL
);

CREATE TABLE `CAR` (
    `CAR_NAME_PK` VARCHAR(20) NOT NULL,
    `COMPANY_NAME` VARCHAR(20) NOT NULL
);

CREATE TABLE `YEARS` (
    `YEAR_PK` VARCHAR(20) NOT NULL,
    `YEAR` VARCHAR(20) NOT NULL
);

CREATE TABLE `OPTIONS` (
    `OPTION_PK` VARCHAR(20) NOT NULL,
    `OPTION` VARCHAR(20) NOT NULL
);

CREATE TABLE `CAR_COMPANY_INFO_YEAR` (
    `CAR_INFORMATION_YEAR_PK` VARCHAR(20) NOT NULL,
    `COMPANY_INFORMATION_FK` VARCHAR(20) NOT NULL,
    `CAR_NAME_FK` VARCHAR(20) NOT NULL,
    `YEAR_FK` VARCHAR(20) NOT NULL,
    `OPTION_FK` VARCHAR(20) NOT NULL
);

-- 테이블에 Primary Key 부여
ALTER TABLE `COMPANY`
    ADD PRIMARY KEY (`COMPANY_INFORMATION_PK`);

ALTER TABLE `CAR`
    ADD PRIMARY KEY (`CAR_NAME_PK`);

ALTER TABLE `YEARS`
    ADD PRIMARY KEY (`YEAR_PK`);

ALTER TABLE `OPTIONS`
    ADD PRIMARY KEY (`OPTION_PK`);

ALTER TABLE `CAR_COMPANY_INFO_YEAR`
    ADD PRIMARY KEY (`CAR_INFORMATION_YEAR_PK`);

-- 테이블에 Foreign Key 부여
ALTER TABLE `CAR`
    ADD CONSTRAINT `FK_CAR_COMPANY`
        FOREIGN KEY (`COMPANY_NAME`)
            REFERENCES `COMPANY`(`COMPANY_NAME`);

ALTER TABLE `CAR_COMPANY_INFO_YEAR`
    ADD CONSTRAINT `FK_COMPANY_INFORMATION`
        FOREIGN KEY (`COMPANY_INFORMATION_FK`)
            REFERENCES `COMPANY`(`COMPANY_INFORMATION_PK`);

ALTER TABLE `CAR_COMPANY_INFO_YEAR`
    ADD CONSTRAINT `FK_CAR_NAME`
        FOREIGN KEY (`CAR_NAME_FK`)
            REFERENCES `CAR`(`CAR_NAME_PK`);

ALTER TABLE `CAR_COMPANY_INFO_YEAR`
    ADD CONSTRAINT `FK_YEAR`
        FOREIGN KEY (`YEAR_FK`)
            REFERENCES `YEARS`(`YEAR_PK`);

ALTER TABLE `CAR_COMPANY_INFO_YEAR`
    ADD CONSTRAINT `FK_OPTION`
        FOREIGN KEY (`OPTION_FK`)
            REFERENCES `YEARS`(`OPTION_PK`);

-- 테이블 삭제

-- 단일 테이블 삭제
DROP TABLE `COMPANY`;
-- 여러 테이블 삭제
DROP TABLE `COMPANY`, `CAR`, `YEARS`, `OPTIONS`, `CAR_COMPANY_INFO_YEAR`;